/*
 * claims_status.js — every insurance claim file and benefit claim connected to the August 28, 2026 collision.
 *
 * This one list drives the "Open Claims" cards on the evidence portal and the claims table in the dossier
 * (regenerated by `npm run build:dossier-pdf`). TO UPDATE A CLAIM: edit its entry. TO ADD ONE: copy an
 * entry. Only "carrier" is required. Dates are YYYY-MM-DD. Keep every field short: the card shows one
 * paragraph ("summary") plus a few facts; the full detail, sources and assessment live in the claim's memo
 * document ("memo"), which the card links to like any other document.
 *
 * Fields:
 *   carrier        insurer or program name                                        (required)
 *   claim_number   exactly as printed on the carrier's screen or letter
 *   policy_number  if known (short)
 *   type           what the claim is for, in a few words
 *   coverage       coverage lines or limits shown on the claim, in one line
 *   status         e.g. "Claim received", "Open", "Pending documents", "Closed", "Not yet filed"
 *   opened         date the claim was reported or first appeared (if known)
 *   incident_date  the incident date as printed on the carrier's claim screen (may be wrong; say so in summary)
 *   last_update    date this entry was last checked against the carrier
 *   adjuster       claim representative
 *   phone / email  contact details
 *   amount_paid    total paid so far (number)
 *   summary        ONE paragraph: what the claim is, where it stands, and the assessment that matters most
 *   next_step      the next action, in one sentence
 *   memo           path (from the repository root) of the claim memo holding the full detail and sources
 *   documents      files that evidence this claim, as paths from the repository root
 */
window.CLAIMS_STATUS = [
  {
    carrier: "Progressive (personal auto policy)",
    claim_number: "26-854858569",
    policy_number: "936659747 (Progressive County Mutual Ins. Co.; named insureds Melody D and Chetan L Dashora)",
    type: "First-party claim: PIP, collision, rental reimbursement, UM/UIM bodily injury and property damage",
    coverage: "UM/UIM BI $250,007/$500,007 · UM/UIM PD $100,007 less $250 · PIP $10,003 · Collision $99 ded · Rental $60/day to $1,800 · Loan/lease payoff 25% of ACV",
    status: "Claim received",
    incident_date: "2026-08-28",
    last_update: "2026-09-04",
    adjuster: "Sloane S (claim rep, per app)",
    phone: "(800) 776-4737 (Progressive claims)",
    amount_paid: 0,
    summary: "The first-party claim under the client's own policy and the practical route to recovery, because the certified crash report records no proof of financial responsibility for the other driver. Two cautions. PIP is already exceeded by the hospital balance alone, so it is an advance, not the medical recovery. The uninsured-motorist benefit is payable only once the other driver's liability is established, and the CR-4 as written assigns the contributing factors to the client, so liability is the work here. Rideshare Use coverage appears on the declarations page, but no written confirmation for this loss, or of which collision deductible applies, exists yet; get it before the total-loss figure is negotiated.",
    next_step: "Obtain the declarations page for the term in force on August 28, 2026 and the Rideshare Use endorsement, submit the dossier as formal UM notice, and get Progressive's coverage position for this loss in writing.",
    memo: "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/CLAIM-MEMO_26-854858569.md",
    documents: [
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/Progressive_Declarations_Page.pdf",
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/2026-09-04_Claim_26-854858569_Summary.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/2026-09-04_Coverage_At_Time_Of_Incident_1.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/2026-09-04_Coverage_At_Time_Of_Incident_2.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/2026-09-04_Payout_Summary_26-854858569.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9383.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9384.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9289.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9290.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9295.png"
    ]
  },
  {
    carrier: "Uber claim, handled by Progressive (Uber/Rasier TNC policy; United Financial Casualty Company)",
    claim_number: "26-343820011",
    policy_number: "Not printed on the claim; the certificate lists UFCC policy 06250080 for the accepted-request period ($1,000,000 CSL; collision at ACV, $2,500 deductible; non-owned autos only)",
    type: "Claim under Uber's transportation-network-company coverage (Tex. Ins. Code ch. 1954)",
    coverage: "Lines opened: Nonowned Medical Payments 2 and Nonowned Collision 2 · UM/UIM not included in any amount (certificate)",
    status: "Claim received",
    incident_date: "2026-08-27",
    last_update: "2026-09-04",
    adjuster: "Sloane S (same rep as the personal-policy claim)",
    phone: "Uber claims portal t.uber.com/claims · Progressive claims (800) 776-4737",
    amount_paid: 0,
    summary: "Uber's TNC coverage through United Financial Casualty, a Progressive company, open on two lines only: non-owned medical payments and non-owned collision. The certificate on file states uninsured-motorist coverage is not included in any amount, so this claim can help with the vehicle and medical payments but cannot be the injury recovery; that stays with the personal policy. Which Uber policy responds turns on whether Uber's own log shows an accepted request at 05:00:15. The client's account says yes; the 5:05 AM cancelled-request receipt is consistent with it but is not proof, and the letters drafted in binder 05 ask Uber for the log. The claim still prints the wrong incident date, August 27, which should be corrected in writing before any coverage position hardens.",
    next_step: "Have Sloane S correct the incident date in writing, send the drafted preservation and § 1954.154 letters, and obtain the policy forms and any written UM/UIM or PIP rejection.",
    memo: "05_Uber_Commercial_Dispatch_And_Coverage/Uber_Claim_26-343820011/CLAIM-MEMO_26-343820011.md",
    documents: [
      "05_Uber_Commercial_Dispatch_And_Coverage/Uber_Claim_26-343820011/2026-09-04_Uber_Driver_Inbox_Next_Steps_Claim_26-343820011.png",
      "05_Uber_Commercial_Dispatch_And_Coverage/Uber_Claim_26-343820011/2026-09-04_Progressive_Web_Claim_Summary_26-343820011.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9385.png",
      "05_Uber_Commercial_Dispatch_And_Coverage/Uber_Texas_Certificate_of_Insurance_COI.pdf",
      "05_Uber_Commercial_Dispatch_And_Coverage/IMG_9364.png"
    ]
  },
  {
    carrier: "Baylor Scott & White Health (hospital account, not an insurance claim)",
    claim_number: "Guarantor #121682647",
    type: "Hospital balance, believed to be the 08/28/2026 emergency visit at Baylor Scott & White Medical Center – Grapevine",
    coverage: "Amount due $13,528.55 (statement dated 09/01/2026); payment plan offered at $752.00 per month",
    status: "Balance outstanding",
    last_update: "2026-09-03",
    phone: "(800) 994-0371 (BSW customer service)",
    summary: "A hospital account, not a claim: $13,528.55 due on the September 1 statement, with no service date and no itemisation on file. It exceeds the $10,003 PIP limit on its own, so a hospital lien under Texas Property Code chapter 55 should be expected and the settlement planned around it. Get the itemised statement before this figure is quoted to anyone, apply for Baylor Scott & White financial assistance now rather than after settlement, and do not sign the $752-a-month plan while the uninsured-motorist claim is open.",
    next_step: "Request the itemised statement and service dates, apply for financial assistance, and ask whether a lien has been filed.",
    memo: "07_Medical_Expenses_And_Billing/ACCOUNT-MEMO_Baylor_Scott_And_White_121682647.md",
    documents: ["07_Medical_Expenses_And_Billing/Baylor_Health_Emergency_Bill.png"]
  },
  {
    carrier: "Uber Optional Injury Protection (Atlantic Specialty Insurance Company)",
    type: "Optional driver injury benefit programme; pays only if the driver enrolled before the collision",
    status: "Not yet filed - enrollment unconfirmed",
    last_update: "2026-09-01",
    phone: "(844) 747-6221, 24 hours",
    summary: "An optional driver injury programme underwritten by Atlantic Specialty; it pays only if the client enrolled before August 28, and enrolment is unconfirmed. It is the one item on this list that the calendar can close: if she was enrolled, notice of injury is due by September 17, 2026, and it would then be the only source that pays her medical costs without a liability fight, a deductible, or a wait for the uninsured-motorist claim. One phone call with the Uber account e-mail settles it either way. The terms and the deadline come from the binder 05 plan and are not yet verified against the policy wording.",
    next_step: "Call (844) 747-6221 with the Uber account e-mail and phone to confirm enrolment on August 28, 2026; if enrolled, give notice of injury before September 17, 2026.",
    memo: "05_Uber_Commercial_Dispatch_And_Coverage/CLAIM-MEMO_Uber_Optional_Injury_Protection.md",
    documents: ["05_Uber_Commercial_Dispatch_And_Coverage/UBER-PLAN.md"]
  }
];
