/*
 * claims_status.js — every insurance claim file and benefit claim connected to the August 28, 2026 collision.
 *
 * This one list drives the "Open Claims" cards on the evidence portal and the claims table in the dossier
 * (regenerated by `npm run build:dossier-pdf`). TO UPDATE A CLAIM: edit its entry. TO ADD ONE: copy an
 * entry. Only "carrier" is required. Dates are YYYY-MM-DD. Keep "notes" factual and say where each fact
 * comes from; anything that is the client's account rather than a document should say so.
 *
 * Fields:
 *   carrier        insurer or program name                                        (required)
 *   claim_number   exactly as printed on the carrier's screen or letter
 *   policy_number  if known
 *   type           what the claim is for (first-party UM/PIP/collision, TNC policy, benefit program, ...)
 *   coverage       coverage lines or limits shown on the claim
 *   status         e.g. "Claim received", "Open", "Pending documents", "Closed", "Not yet filed"
 *   opened         date the claim was reported or first appeared (if known)
 *   incident_date  the incident date as printed on the carrier's claim screen (may be wrong; say so in notes)
 *   last_update    date this entry was last checked against the carrier
 *   adjuster       claim representative
 *   phone / email  contact details
 *   amount_paid    total paid so far (number)
 *   next_step      the next action, in one sentence
 *   notes          facts and their sources; discrepancies to raise with the adjuster
 *   documents      files that evidence this claim, as paths from the repository root
 */
window.CLAIMS_STATUS = [
  {
    carrier: "Progressive (personal auto policy)",
    claim_number: "26-854858569",
    policy_number: "936659747 (declarations page on file, underwritten by Progressive County Mutual Ins Co; the copy on file is the renewal term Sep 1, 2026 to Mar 1, 2027, copy dated Sep 4, 2026, and its coverages match the app's Coverage at Time of Incident screen for Aug 28, 2026)",
    type: "First-party claim under the client's own policy: PIP, Collision, Rental Reimbursement. UM/UIM bodily injury and property damage are on the policy (the CR-4 records no proof of financial responsibility for the adverse driver); the app itself notes its coverage list is informational.",
    coverage: "Coverage at time of incident (app, Aug 28, 2026): BI $250,007/$500,007 · PD $100,007 · PIP $10,003 · UM/UIM BI $250,007/$500,007 · UM/UIM PD $100,007 less $250 · Collision and Comprehensive $99 ded · Rental Reimbursement $60/day, 30 days ($1,800) · Loan/Lease Payoff 25% of ACV, $0 ded · Roadside with Trip Interruption · Progressive Vehicle Protection. Declarations page: vehicle has Rideshare Use coverage; primary use Pleasure/Personal, Rideshare; lienholder Capital One Auto Fin.",
    status: "Claim received",
    incident_date: "2026-08-28",
    last_update: "2026-09-04",
    adjuster: "Sloane S (claim rep, per app)",
    phone: "(800) 776-4737 (Progressive claims; the app shows only 'Call Your Rep')",
    amount_paid: 0,
    next_step: "Obtain the declarations page for the term in force on Aug 28, 2026 (presumably Mar 1 to Sep 1, 2026, the preceding six-month term; the copy on file is the renewal); submit the dossier as formal notice of the UM bodily-injury and property-damage claim; confirm the $99 collision deductible applies under Rideshare Use coverage; request written confirmation of Period 2 coverage.",
    notes: "Incident date on the claim: Friday, August 28, 2026 (rechecked 09/04/2026). Payout Summary (09/04/2026): PIP $0.00, Collision $0.00, Rental Reimbursement $0.00; total $0.00 paid to date. Named insureds on the declarations page: Melody D Dashora and Chetan L Dashora.",
    documents: [
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9383.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9384.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9289.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9290.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9295.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/Progressive_Declarations_Page.pdf",
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/2026-09-04_Claim_26-854858569_Summary.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/2026-09-04_Coverage_At_Time_Of_Incident_1.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/2026-09-04_Coverage_At_Time_Of_Incident_2.png",
      "08_Progressive_Policy_And_First_Party_Coverage/Claim_26-854858569_And_Policy/2026-09-04_Payout_Summary_26-854858569.png"
    ]
  },
  {
    carrier: "Uber claim — handled by Progressive (Uber/Rasier TNC policy; the certificate names United Financial Casualty Company)",
    claim_number: "26-343820011",
    policy_number: "Not printed on the claim screen. Uber's certificate of insurance (binder 05) lists United Financial Casualty Company (NAIC 11770; producer Progressive) policy 06250080 for a driver who has accepted a request (en route to pickup or on trip): $1,000,000 combined single limit, comprehensive and collision at ACV with a $2,500 deductible, non-owned autos only.",
    type: "Claim under Uber's transportation-network-company coverage (Tex. Ins. Code ch. 1954; § 1954.053 if the accepted-request period is confirmed). Uber's in-app notice 'Next steps for your claim' states: 'We work with Progressive to provide protection on your behalf while you operate on the Uber app ... Claim number: 26-343820011'. Client's account: she had accepted a pickup request and was driving to it when struck, and the rider canceled after the collision (she describes the request as a reservation; the receipt shows the product only as UberX).",
    coverage: "Coverage lines shown on the claim: Nonowned Medical Payments 2 (Melody Dashora) and Nonowned Collision 2 (2025 Volkswagen Atlas). The COI states UM/UIM is not included in any amount on either Uber policy.",
    status: "Claim received",
    incident_date: "2026-08-27",
    last_update: "2026-09-04",
    adjuster: "Sloane S (same claim rep as the personal-policy claim, per the web claim summary)",
    phone: "Uber claims portal: t.uber.com/claims · Progressive claims (800) 776-4737",
    amount_paid: 0,
    next_step: "Have Sloane S correct the incident date in writing (the claim still shows August 27, 2026 on 09/04/2026; the client says it first showed August 30; the collision was August 28, 2026 at 05:00); obtain the TNC policy forms and any written UM/UIM or PIP rejection (Tex. Ins. Code ch. 1952).",
    notes: "Uber Driver app inbox notice (binder 05) gives claim number 26-343820011 and states 'We work with Progressive to provide protection on your behalf while you operate on the Uber app'. Progressive web claim summary (policyservicing.apps.progressive.com, 09/01 and 09/04/2026): 'We've received your claim', incident date August 27, 2026, payout $0.00, coverage lines 'Nonowned Medical Payments 2' and 'Nonowned Collision 2' (the Uber/Rasier certificate covers non-owned autos only). The accepted request is the client's account (she describes it as a reservation); the canceled-trip receipt shows only 'UberX · Aug 28, 2026 · 5:05 AM', upfront fare $12.07, pickup and drop-off both 'N State Highway 121, Coppell' beside the Aloft Dallas DFW Airport Grapevine. Uber's trip log (request, accept and cancel times) is the corroborating record to obtain. Preservation letters to Uber Technologies, Inc. and Rasier, LLC were drafted on 09/04/2026 (binder 05, Preservation_Letters_And_Statutory_Requests/); as of this entry they are unsent drafts and the § 1954.154 log-on-time request has not been written.",
    documents: [
      "08_Progressive_Policy_And_First_Party_Coverage/Progressive_Policy_Declarations_And_Endorsements/IMG_9385.png",
      "05_Uber_Commercial_Dispatch_And_Coverage/Uber_Texas_Certificate_of_Insurance_COI.pdf",
      "05_Uber_Commercial_Dispatch_And_Coverage/IMG_9364.png",
      "05_Uber_Commercial_Dispatch_And_Coverage/Uber_Claim_26-343820011/2026-09-04_Uber_Driver_Inbox_Next_Steps_Claim_26-343820011.png",
      "05_Uber_Commercial_Dispatch_And_Coverage/Uber_Claim_26-343820011/2026-09-04_Progressive_Web_Claim_Summary_26-343820011.png"
    ]
  },
  {
    carrier: "Baylor Scott & White Health (hospital account, not an insurance claim)",
    claim_number: "Guarantor #121682647",
    type: "Hospital balance believed to be the 08/28/2026 Baylor Scott & White Medical Center – Grapevine emergency visit (the billing screenshot shows no service date)",
    coverage: "Amount due $13,528.55 (statement dated 09/01/2026); payment plan offered at $752.00 per month; itemized statement not yet obtained",
    status: "Balance outstanding",
    last_update: "2026-09-03",
    phone: "(800) 994-0371 (BSW customer service)",
    next_step: "Request the itemized statement and apply for financial assistance before any settlement distribution; balance exceeds the $10,003 PIP limit, so a hospital lien (Tex. Prop. Code ch. 55) should be expected.",
    documents: ["07_Medical_Expenses_And_Billing/Baylor_Health_Emergency_Bill.png"]
  },
  {
    carrier: "Uber Optional Injury Protection (Atlantic Specialty Insurance Company)",
    type: "Driver injury benefit program; pays only if the driver was enrolled before the collision",
    status: "Not yet filed - enrollment unconfirmed",
    last_update: "2026-09-01",
    phone: "(844) 747-6221, 24/7",
    next_step: "Call with the Uber account email and phone to confirm whether the client was enrolled on 08/28/2026; if so, give notice of injury before the 20-day deadline on 2026-09-17.",
    notes: "Source: binder 05 evidence-and-insurance plan (UBER-PLAN.md, 09/01/2026). Deadline and enrollment condition are as stated in that plan, not verified against Atlantic Specialty's terms.",
    documents: ["05_Uber_Commercial_Dispatch_And_Coverage/UBER-PLAN.md"]
  }
];
